export const profileDefinition = {
    metaUrl: 'https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_profile.htm',
    main: [
        'custom',
        'description',
        'fullName',
        'userLicense',
    ],
    singleFiles: [
        'applicationVisibilities',
        'categoryGroupVisibilities',
        'classAccesses',
        'customMetadataTypeAccesses',
        'customPermissions',
        'customSettingAccesses',
        'externalDataSourceAccesses',
        'flowAccesses',
        'layoutAssignments',
        // TODO 'loginHours',
        'loginIpRanges',
        'pageAccesses',
        // TODO 'profileActionOverrides',
        'tabVisibilities',
        'userPermissions',
    ],
    directories: [
        'fieldPermissions',
        'loginFlows',
        'objectPermissions',
        'recordTypeVisibilities',
    ],
    ignore: [
        '$',
    ],
    sortKeys: {
        'applicationVisibilities': 'application',
        'categoryGroupVisibilities': 'dataCategoryGroup',
        'classAccesses': 'apexClass',
        'customMetadataTypeAccesses': 'name',
        'customPermissions': 'name',
        'customSettingAccesses': 'name',
        'externalDataSourceAccesses': 'externalDataSource',
        'fieldPermissions': 'field',
        'flowAccesses': 'flow',
        'layoutAssignments': 'layout',
        'loginFlows': 'friendlyName',
        'loginIpRanges': 'startAddress',
        'objectPermissions': 'object',
        'pageAccesses': 'apexPage',
        'profileActionOverrides': 'pageOrSobjectType',
        'recordTypeVisibilities': 'recordType',
        'tabVisibilities': 'tab',
        'userPermissions': 'name',        
    }
}
