export const metadataDefinition = {
	metaUrl:
		'https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_permissionset.htm',
	directory: 'permissionsets',
	filetype: 'permissionset',
	root: 'PermissionSet',
	type: 'PermissionSet',
	alias: 'permset',
	main: [
		'label',
		'description',
		'custom',
		'hasActivationRequired',
		'license',
		'userLicense', // Replaced by license
		'$',
	],
	singleFiles: [
		'applicationVisibilities',
		'classAccesses',
		'customMetadataTypeAccesses',
		'customPermissions',
		'customSettingAccesses',
		'externalDataSourceAccesses',
		'flowAccesses',
		'pageAccesses',
		'tabSettings',
		'userPermissions',
	],
	directories: [
		'fieldPermissions',
		'objectPermissions',
		'recordTypeVisibilities',
	],
	splitObjects: [
		'fieldPermissions',
		'objectPermissions',
		'recordTypeVisibilities',
	],
	sortKeys: {
		applicationVisibilities: 'application',
		classAccesses: 'apexClass',
		customMetadataTypeAccesses: 'name',
		customPermissions: 'name',
		customSettingAccesses: 'name',
		externalDataSourceAccesses: 'externalDataSource',
		fieldPermissions: 'field',
		flowAccesses: 'flow',
		objectPermissions: 'object',
		pageAccesses: 'apexPage',
		recordTypeVisibilities: 'recordType',
		tabSettings: 'tab',
		userPermissions: 'name',
	},
	keyOrder: {
		applicationVisibilities: ['application', 'visible'],
		classAccesses: ['apexClass', 'enabled'],
		customMetadataTypeAccesses: ['name', 'enabled'],
		customPermissions: ['name', 'enabled'],
		customSettingAccesses: ['name', 'enabled'],
		externalDataSourceAccesses: ['externalDataSource', 'enabled'],
		fieldPermissions: ['field', 'editable', 'readable'],
		flowAccesses: ['flow', 'enabled'],
		objectPermissions: [
			'object',
			'allowCreate',
			'allowRead',
			'allowEdit',
			'allowDelete',
			'viewAllRecords',
			'modifyAllRecords',
		],
		pageAccesses: ['apexPage', 'enabled'],
		recordTypeVisibilities: ['recordType', 'visible'],
		tabSettings: ['tab', 'visibility'],
		userPermissions: ['name', 'enabled'],
	},
	delta: false,
}
