import type { MetadataDefinition } from '../types/metadata.js'

export const metadataDefinition: MetadataDefinition = {
	metaUrl:
		'https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_permissionset.htm',
	directory: 'permissionsets',
	filetype: 'permissionset',
	root: 'PermissionSet',
	type: 'PermissionSet',
	alias: 'permset',
	main: [
		'label',
		'description',
		'custom',
		'hasActivationRequired',
		'license',
		'userLicense', // Replaced by license
		'$',
	],
	singleFiles: [
		'agentAccesses', // API v63, Summer '25
		'applicationVisibilities',
		'classAccesses',
		'customMetadataTypeAccesses',
		'customPermissions',
		'customSettingAccesses',
		'externalCredentialPrincipalAccesses',
		'externalDataSourceAccesses',
		'flowAccesses',
		'pageAccesses',
		'servicePresenceStatusAccesses', // API v64, Summer '25
		'tabSettings',
		'userPermissions',
	],
	directories: [
		'fieldPermissions',
		'objectPermissions',
		'recordTypeVisibilities',
	],
	splitObjects: [
		'fieldPermissions',
		'objectPermissions',
		'recordTypeVisibilities',
	],
	sortKeys: {
		agentAccesses: 'agent',
		applicationVisibilities: 'application',
		classAccesses: 'apexClass',
		customMetadataTypeAccesses: 'name',
		customPermissions: 'name',
		customSettingAccesses: 'name',
		externalCredentialPrincipalAccesses: 'externalCredentialPrincipal',
		externalDataSourceAccesses: 'externalDataSource',
		fieldPermissions: 'field',
		flowAccesses: 'flow',
		objectPermissions: 'object',
		pageAccesses: 'apexPage',
		recordTypeVisibilities: 'recordType',
		servicePresenceStatusAccesses: 'servicePresenceStatus',
		tabSettings: 'tab',
		userPermissions: 'name',
	},
	keyOrder: {
		agentAccesses: ['agent', 'enabled'],
		applicationVisibilities: ['application', 'visible'],
		classAccesses: ['apexClass', 'enabled'],
		customMetadataTypeAccesses: ['name', 'enabled'],
		customPermissions: ['name', 'enabled'],
		customSettingAccesses: ['name', 'enabled'],
		externalCredentialPrincipalAccesses: [
			'externalCredentialPrincipal',
			'enabled',
		],
		externalDataSourceAccesses: ['externalDataSource', 'enabled'],
		fieldPermissions: ['field', 'editable', 'readable'],
		flowAccesses: ['flow', 'enabled'],
		objectPermissions: [
			'object',
			'allowCreate',
			'allowRead',
			'allowEdit',
			'allowDelete',
			'viewAllRecords',
			'modifyAllRecords',
			'viewAllFields', // API v63, Spring '25
		],
		pageAccesses: ['apexPage', 'enabled'],
		recordTypeVisibilities: [
			'recordType',
			'default',
			'visible',
			'personAccountDefault',
		],
		servicePresenceStatusAccesses: ['servicePresenceStatus', 'enabled'],
		tabSettings: ['tab', 'visibility'],
		userPermissions: ['name', 'enabled'],
	},
	delta: false,
}
