applicationVisibilities:
  - application: standard__AllTabSet
    default: false
    visible: false
  - application: standard__AppLauncher
    default: false
    visible: false
  - application: standard__Chatter
    default: false
    visible: false
  - application: standard__Community
    default: false
    visible: false
  - application: standard__Content
    default: false
    visible: false
  - application: standard__DataManager
    default: false
    visible: false
  - application: standard__Insights
    default: false
    visible: false
  - application: standard__LightningBolt
    default: false
    visible: false
  - application: standard__LightningInstrumentation
    default: false
    visible: false
  - application: standard__LightningSales
    default: false
    visible: false
  - application: standard__LightningSalesConsole
    default: false
    visible: false
  - application: standard__LightningScheduler
    default: false
    visible: false
  - application: standard__LightningService
    default: false
    visible: false
  - application: standard__Marketing
    default: false
    visible: false
  - application: standard__Platform
    default: true
    visible: true
  - application: standard__QueueManagement
    default: false
    visible: false
  - application: standard__RevenueCloudConsole
    default: false
    visible: false
  - application: standard__Sales
    default: false
    visible: false
  - application: standard__SalesforceCMS
    default: false
    visible: false
  - application: standard__Service
    default: false
    visible: false
  - application: standard__ServiceConsole
    default: false
    visible: false
  - application: standard__Sites
    default: false
    visible: false
